# Form implementation generated from reading ui file 'D:\BitBreaker\appdv.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 390, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(False)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    \n"
"    border: 2px solid black;\n"
"    border-radius: 20px;\n"
"    text-color: #f9e612;\n"
"    \n"
"    \n"
"    background-color: rgb(252, 251, 231);\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(190, 247, 223);\n"
"    \n"
"    \n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(252, 251, 231);\n"
"\n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.background = QtWidgets.QLabel(parent=self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 640, 480))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.background.setFont(font)
        self.background.setStyleSheet("border-image: url(:/newPrefix/dđ.png);")
        self.background.setText("")
        self.background.setObjectName("background")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(330, 260, 111, 31))
        self.comboBox.setMinimumSize(QtCore.QSize(0, 31))
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.comboBox.setFont(font)
        self.comboBox.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.comboBox.setStyleSheet("    border: 2px solid black;\n"
"    border-radius: 20px;\n"
"    text-color: #f9e612;\n"
"    \n"
"    \n"
"    background-color: rgb(252, 251, 231);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 260, 151, 31))
        self.label.setMinimumSize(QtCore.QSize(0, 31))
        self.label.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setStyleSheet("border: 2px solid black;\n"
"border-radius: 20px;\n"
"background-color: rgb(65, 196, 172);\n"
"    \n"
"    ")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(470, 180, 31, 31))
        self.pushButton_2.setMinimumSize(QtCore.QSize(31, 31))
        self.pushButton_2.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    \n"
"    border: 2px solid black;\n"
"    border-radius: 20px;\n"
"    text-color: #f9e612;\n"
"    \n"
"    \n"
"    background-color: rgb(252, 251, 231);\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(190, 247, 223);\n"
"    \n"
"    \n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(252, 251, 231);\n"
"\n"
"\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(220, 180, 251, 31))
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 31))
        self.lineEdit_3.setSizeIncrement(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("    border: 2px solid black;\n"
"    border-radius: 20px;\n"
"    text-color: #f9e612;\n"
"    \n"
"    \n"
"    background-color: rgb(252, 251, 231);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(470, 220, 31, 31))
        self.pushButton_4.setMinimumSize(QtCore.QSize(31, 31))
        self.pushButton_4.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    \n"
"    border: 2px solid black;\n"
"    border-radius: 20px;\n"
"    text-color: #f9e612;\n"
"    \n"
"    \n"
"    background-color: rgb(252, 251, 231);\n"
"    \n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(190, 247, 223);\n"
"    \n"
"    \n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(252, 251, 231);\n"
"\n"
"\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 300, 331, 61))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: 2px solid black;\n"
"border-radius: 10px;\n"
"background-color: rgb(192, 241, 220);\n"
"    \n"
"    ")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(220, 220, 251, 31))
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 31))
        self.lineEdit_4.setSizeIncrement(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("    border: 2px solid black;\n"
"    border-radius: 20px;\n"
"    text-color: #f9e612;\n"
"    \n"
"    \n"
"    background-color: rgb(252, 251, 231);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 180, 71, 31))
        self.label_3.setMinimumSize(QtCore.QSize(0, 31))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border: 2px solid black;\n"
"border-radius: 20px;\n"
"background-color: rgb(65, 196, 172);\n"
"    \n"
"    ")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(180, 220, 41, 31))
        self.label_4.setMinimumSize(QtCore.QSize(0, 31))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border: 2px solid black;\n"
"border-radius: 20px;\n"
"background-color: rgb(65, 196, 172);\n"
"    \n"
"    ")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(440, 260, 41, 31))
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 31))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("    border: 2px solid black;\n"
"    border-radius: 20px;\n"
"    text-color: #f9e612;\n"
"    \n"
"    \n"
"    background-color: rgb(252, 251, 231);")
        self.lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.background.raise_()
        self.pushButton.raise_()
        self.comboBox.raise_()
        self.label.raise_()
        self.pushButton_2.raise_()
        self.lineEdit_3.raise_()
        self.pushButton_4.raise_()
        self.label_2.raise_()
        self.lineEdit_4.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.lineEdit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Chạy"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Thuật toán 1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Thuật toán 2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Thuật toán 3"))
        self.label.setText(_translate("MainWindow", "Thuật toán sử dụng"))
        self.pushButton_2.setText(_translate("MainWindow", "..."))
        self.pushButton_4.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "Kết quả"))
        self.label_3.setText(_translate("MainWindow", "Nguồn ảnh"))
        self.label_4.setText(_translate("MainWindow", "Ảnh"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
